tab component 구현
ai-paas/mlops-web pull request #7
Opened 2024-09-30 05:07 UTC by lalalayu87

2024-09-30 05:12 UTC, choikiyeop commented on packages/ui/src/tab/tab.tsx
> +      className={`${isActive ? 'bg-blue-500 text-white' : 'tex-black bg-white'} mx-1 rounded-md px-4 py-2`}
tex-black 오타 발견!

2024-09-30 05:13 UTC, choikiyeop commented on packages/ui/src/tab/tab.tsx
> +interface TanPanelProps {
TanPanelProps 오타

2024-09-30 05:21 UTC, choikiyeop requested changes
화이팅~

2024-09-30 05:21 UTC, choikiyeop commented on packages/ui/src/tab/tab.tsx
> +  return <div role="tabpenel">{children}</div>;
tabpenel 오타

2024-09-30 05:21 UTC, choikiyeop commented on packages/ui/src/tab/tab.tsx
> +interface TanPanelProps {
TanPanelProps 오타

2024-09-30 05:21 UTC, choikiyeop commented on packages/ui/src/tab/tab.tsx
> +      className={`${isActive ? 'bg-blue-500 text-white' : 'tex-black bg-white'} mx-1 rounded-md px-4 py-2`}
tex-black 오타 발견!

2024-09-30 05:21 UTC, choikiyeop commented on packages/ui/src/tab/tab.tsx
> +const Tab: React.FC<TabProps> = ({ tabId, children }) => {
전체적으로 타입 지정이 정확하지 않아요.
이 코드에서 Tab의 높이를 지정하려면 어떻게 해야할까요??
의존성 역전을 생각해보시면 좋을 것 같습니다.

2024-09-30 05:22 UTC, lalalayu87 commented on packages/ui/src/tab/tab.tsx
> +const Tab: React.FC<TabProps> = ({ tabId, children }) => {
네 쓰앵님

2024-10-07 07:54 UTC, lalalayu87 commented
pr 부탁드립니다....!

2024-10-07 08:03 UTC, closed without merging